<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="这是用户管理系统测试套件" duration-ms="19160" started-at="2020-06-24T06:12:27Z" finished-at="2020-06-24T06:12:46Z">
    <groups>
      <group name="Login">
        <method signature="LoginTest.loginTrue()[pri:0, instance:com.xiaoyu.cases.LoginTest@34ce8af7]" name="loginTrue" class="com.xiaoyu.cases.LoginTest"/>
      </group> <!-- Login -->
    </groups>
    <test name="这是用户管理系统测试用例" duration-ms="19160" started-at="2020-06-24T06:12:27Z" finished-at="2020-06-24T06:12:46Z">
      <class name="com.xiaoyu.cases.GetUserInfoListTest">
        <test-method status="FAIL" signature="getUserListInfo()[pri:0, instance:com.xiaoyu.cases.GetUserInfoListTest@36d64342]" name="getUserListInfo" duration-ms="24" depends-on-groups="Login" started-at="2020-06-24T14:12:46Z" description="获取性别为男的用户信息" finished-at="2020-06-24T14:12:46Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONArray text must start with '[' at 1 [character 2 line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONArray.<init>(JSONArray.java:109)
	at org.json.JSONArray.<init>(JSONArray.java:162)
	at com.xiaoyu.cases.GetUserInfoListTest.getJsonResult(GetUserInfoListTest.java:74)
	at com.xiaoyu.cases.GetUserInfoListTest.getUserListInfo(GetUserInfoListTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:93)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserListInfo -->
      </class> <!-- com.xiaoyu.cases.GetUserInfoListTest -->
      <class name="com.xiaoyu.cases.AddUserTest">
        <test-method status="PASS" signature="addUser()[pri:0, instance:com.xiaoyu.cases.AddUserTest@b684286]" name="addUser" duration-ms="5042" depends-on-groups="Login" started-at="2020-06-24T14:12:28Z" description="添加用户接口接口" finished-at="2020-06-24T14:12:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUser -->
      </class> <!-- com.xiaoyu.cases.AddUserTest -->
      <class name="com.xiaoyu.cases.UpdateUserInforTest">
        <test-method status="PASS" signature="updateUserInfo()[pri:0, instance:com.xiaoyu.cases.UpdateUserInforTest@7f63425a]" name="updateUserInfo" duration-ms="5050" depends-on-groups="Login" started-at="2020-06-24T14:12:36Z" description="更改用户信息" finished-at="2020-06-24T14:12:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUserInfo -->
        <test-method status="PASS" signature="deleteUser()[pri:0, instance:com.xiaoyu.cases.UpdateUserInforTest@7f63425a]" name="deleteUser" duration-ms="5026" depends-on-groups="Login" started-at="2020-06-24T14:12:41Z" description="删除用户" finished-at="2020-06-24T14:12:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- com.xiaoyu.cases.UpdateUserInforTest -->
      <class name="com.xiaoyu.cases.GetUserInfoTest">
        <test-method status="PASS" signature="getUserInfo()[pri:0, instance:com.xiaoyu.cases.GetUserInfoTest@3f3afe78]" name="getUserInfo" duration-ms="3033" depends-on-groups="Login" started-at="2020-06-24T14:12:33Z" description="获取 userId 为1的用户信息" finished-at="2020-06-24T14:12:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserInfo -->
      </class> <!-- com.xiaoyu.cases.GetUserInfoTest -->
      <class name="com.xiaoyu.cases.LoginTest">
        <test-method status="PASS" signature="beforTest()[pri:0, instance:com.xiaoyu.cases.LoginTest@34ce8af7]" name="beforTest" is-config="true" duration-ms="43" started-at="2020-06-24T14:12:27Z" description="这是测试前准备工作" finished-at="2020-06-24T14:12:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforTest -->
        <test-method status="PASS" signature="loginTrue()[pri:0, instance:com.xiaoyu.cases.LoginTest@34ce8af7]" name="loginTrue" duration-ms="891" started-at="2020-06-24T14:12:27Z" description="用户成功登陆接口" finished-at="2020-06-24T14:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTrue -->
        <test-method status="PASS" signature="loginFalse()[pri:0, instance:com.xiaoyu.cases.LoginTest@34ce8af7]" name="loginFalse" duration-ms="37" started-at="2020-06-24T14:12:28Z" description="用户登录失败接口" finished-at="2020-06-24T14:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFalse -->
      </class> <!-- com.xiaoyu.cases.LoginTest -->
    </test> <!-- 这是用户管理系统测试用例 -->
  </suite> <!-- 这是用户管理系统测试套件 -->
</testng-results>
